api_key: YOUR_YOUTUBE_API_KEY_HERE
cache_dir: .cache
cache_enabled: true
export_formats:
- json
- html
max_playlists: 100
output_dir: results
parallel_search: true
search_strategies:
- exact_title
- channel_playlists
- title_channel
- keyword_search
